version: '3.4'

services:

  go-otel-demo-app:
    image: go-otel-demo
    build:
      context: ./go-otel-demo
    environment:
      - RAILS_APP_URL=http://rails-dd-demo-app:3000
      - TRACING_RECEIVER_ENDPOINT=datadog-agent:4317
    ports:
      - 3002:3002

  rails-dd-demo-app:
    image: rails-dd-demo
    build:
      context: ./rails_dd_demo
    environment:
      - RAILS_ENV=test
      - DD_ENV=development
      - DD_SERVICE=rails-dd-demo
      - DD_VERSION=1.0.0
      - DD_AGENT_HOST=datadog-agent
      - DD_TRACE_AGENT_PORT=8126
    ports:
      - 3000:3000

  datadog-agent:
    image: datadog/agent:7.40.0
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_SITE=datadoghq.eu
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      # misc
      - DD_LOG_LEVEL=info
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "5003:5003"
      - "8126:8126"
      - "4317:4317"